### ISSUE TITLE
line 66 : [ui_scalar]: default scalar value is outside interval

### ISSUE THREAD

**Issue by BrigitteMaillere** [loic-fejoz/loic-fejoz-fabmoments#1]
Hi,
great code , thanks Loic.

a typo at line 66  ? 
`radius = ui_scalar('radius', 5, 10, 100)`

perhaps you wanted  :
`radius = ui_scalar('radius', 10, 5, 100)`

**Comment by loic-fejoz** [comment]
Yes indeed @BrigitteMaillere I always got ui_scalar wrong.
Thanks for reporting, I will correct it soon.
